version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bookwyrm
      POSTGRES_PASSWORD: bookwyrm
      POSTGRES_DB: bookwyrm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookwyrm"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: development-dependencies-env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      DATABASE_URL: "postgresql://bookwyrm:bookwyrm@db:5432/bookwyrm?schema=public"
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 