# For development purposes only #
# This is not a production-ready configuration #
version: "3.9"

services:
  bookwyrm-db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookwyrm
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bookwyrm-app:
    build:
      context: .
    depends_on:
      bookwyrm-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@bookwyrm-db:5432/bookwyrm?schema=public
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: ./docker-entrypoint.sh

volumes:
  pgdata:
